# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 16:52
from __future__ import unicode_literals

from django.db import migrations, models
# import django.db.model.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('occupation', models.IntegerField()),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
    ]
