# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 17:03
from __future__ import unicode_literals

from django.db import migrations

import csv
import datetime


def import_movie_data(apps, schema_editor):
    Movie = apps.get_model('movie_rate', 'Movie')
    Rater = apps.get_model("movie_rate", 'Rater')
    Rating = apps.get_model('movie_rate', 'Rating')

    movies = {}
    raters = {}


    with open('../ml-100k/u.item', encoding='latin_1') as f:
            reader = csv.reader(f, delimiter='|')
            for row in reader:
                movie, created = Movie.objects.get_or_create(
                    id=int(row[0]),
                    title=row[1])
                movies[movie.id]=movie
                    # release_date=row[],
                    # video_release_date=row[],
                    # imdb_url=row[],
                    # blank=row[],
                    # action=row[],
                    # adventure=row[],
                    # animation=row[],
                    # childrens=row[],
                    # comedy=row[],
                    # crime=row[],
                    # documentary=row[],
                    # drama=row[],
                    # fantasy=row[],
                    # film_noir=row[],
                    # horror=row[],
                    # musical=row[],
                    # mystery=row[],
                    # romance=row[],
                    # sci_fi=row[],
                    # thriller=row[],
                    # war=row[],
                    # western=row[]



    with open('../ml-100k/u.user') as f:
            reader = csv.reader(f, delimiter='|')
            for row in reader:
                # print(row[1])
                rater, created = Rater.objects.get_or_create(
                    id=int(row[0]),
                    age=int(row[1]),
                    gender=row[2],
                    occupation=row[3],
                    zipcode=row[4]
                    )
                raters[rater.id] = rater


    with open('../ml-100k/u.data') as f:
            reader = csv.reader(f, delimiter='\t')
            for row in reader:
                movie_id = int(row[1])
                rater_id = int(row[0])
                timestamp = datetime.datetime.fromtimestamp(float(row[3]))
                _, created = Rating.objects.get_or_create(
                    rating=int(row[2]),
                    timestamp=timestamp,
                    movie=movies[movie_id],
                    rater=raters[rater_id]
                    )



class Migration(migrations.Migration):

    dependencies = [
        ('movie_rate', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_movie_data)
    ]
