# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 22:45
from __future__ import unicode_literals

from django.db import migrations

import csv
# !!!!  test this in terminal - read a file in, then see if it can go in Movie.obj

 def import_movie_data(apps, schema_editor):
	movie = apps.get_model(‘movie_lens’, ‘Movie’)
	rater = apps.get_model(‘movie_lens’, 'Rater')
	rating = apps.get_model(‘movie_lens’, 'Rating')


    with open('http://files.grouplens.org/datasets/movielens/ml-100k/u.item') as f:
            reader = csv.reader(f, delimiter='|')
            for row in reader:
                _, created = Movie.objects.get_or_create(
                    id=row['movie id'],
                    title=row['movie title'],
                    release_date=row['rel date'],
                    video_release_date=row["vid rel date"],
                    imdb_url=row["IMDb URL"],
                    blank=row["blank"],
                    action=row["Action"],
                    adventure=row["Adventure"],
                    animation=row["Animation"],
                    childrens=row["Children's"],
                    comedy=row["Comedy"],
                    crime=row["Crime"],
                    documentary=row["Documentary"],
                    drama=row["Drama"],
                    fantasy=row["Fantasy"],
                    film_noir=row["Film-Noir"],
                    horror=row["Horror"],
                    musical=row["Musical"],
                    mystery=row["Mystery"],
                    romance=row["Romance"],
                    sci_fi=row["Sci-Fi"],
                    thriller=row["Thriller"],
                    war=row["War"],
                    western=row["Western"]
                    )

                _.save()

    with open('http://files.grouplens.org/datasets/movielens/ml-100k/u.user') as f:
            reader = csv.reader(f, delimiter='|')
            for row in reader:
                _, created = Rater.objects.get_or_create(
                    id=row['user id'],
                    age=row['age'],
                    gender=row['gender'],
                    occupation=row['occupation'],
                    zip_code=row['zip code']
                    )

                _.save()

    with open('http://files.grouplens.org/datasets/movielens/ml-100k/u.data') as f:
            reader = csv.reader(f, delimiter='\t')
            for row in reader:
                _, created = Rating.objects.get_or_create(
                    rating=row['rating'],
                    timestamp=row['timestamp'],
                    movie=movies[row['item id']],
                    rater=raters[row['user id']]
                    )

                _.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rate', '0001_initial'),
    ]

    operations = [


    ]
