# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 17:03
from __future__ import unicode_literals

from django.db import migrations

import csv

def import_movie_data(apps, schema_editor):
    # movie = apps.get_model('movie_rate', 'Movie')
    rater = apps.get_model("movie_rate", 'Rater')
    # rating = apps.get_model('movie_rate', 'Rating')


    # with open('../../../ml-100k/u.item') as f:
    #         reader = csv.reader(f, delimiter='|')
    #         for row in reader:
    #             _, created = Movie.objects.get_or_create(
    #                 id=row[],
    #                 title=row[],
    #                 release_date=row[],
    #                 video_release_date=row[],
    #                 imdb_url=row[],
    #                 blank=row[],
    #                 action=row[],
    #                 adventure=row[],
    #                 animation=row[],
    #                 childrens=row[],
    #                 comedy=row[],
    #                 crime=row[],
    #                 documentary=row[],
    #                 drama=row[],
    #                 fantasy=row[],
    #                 film_noir=row[],
    #                 horror=row[],
    #                 musical=row[],
    #                 mystery=row[],
    #                 romance=row[],
    #                 sci_fi=row[],
    #                 thriller=row[],
    #                 war=row[],
    #                 western=row[]
    #                 )
    #
    #             _.save()

    with open('../../../ml-100k/u.user') as f:
            reader = csv.reader(f, delimiter='|')
            for row in reader:
                print(row[1])
                _, created = rater.objects.get_or_create(
                    id=row[0],
                    age=int(row[1]),
                    gender=row[2],
                    occupation=int(row[3]),
                    zipcode=row[4]
                    )


    # with open('../../../ml-100k/u.data') as f:
    #         reader = csv.reader(f, delimiter='\t')
    #         for row in reader:
    #             _, created = Rating.objects.get_or_create(
    #                 rating=row[],
    #                 timestamp=row[],
    #                 movie=movies[row[]],
    #                 rater=raters[row[]]
    #                 )
    #
    #             _.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rate', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_movie_data)
    ]
